version: '3.4'

services:
  meowy:
    image: meowy
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    command: 'npm run dev'
